name: Check stocks & notify

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-stocks-and-notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm i
    - run: node index.js
      env:
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        TILL_ID: ${{ secrets.TILL_ID }}
        TILL_KEY: ${{ secrets.TILL_KEY }}
