# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run periodically.

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm i
    - run: node index.js
      env:
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        TILL_ID: ${{ secrets.TILL_ID }}
        TILL_KEY: ${{ secrets.TILL_KEY }}
